-- Active: 1700455865595@@127.0.0.1@3306@FMPS

-- 1. Find the total investment for each user
SELECT UserID, SUM(PurchasePrice * Quantity) AS TotalInvestment
FROM USER_INVESTMENT
GROUP BY UserID;

-- 2. Find the user who has the highest total investment
SELECT UserID, SUM(PurchasePrice * Quantity) AS TotalInvestment
FROM USER_INVESTMENT
GROUP BY UserID
ORDER BY TotalInvestment DESC
LIMIT 1;

-- 3. Find the financial instrument with the highest current market price
SELECT Name, CurrentMarketPrice
FROM FINANCIAL_INSTRUMENT
ORDER BY CurrentMarketPrice DESC
LIMIT 1;

-- 4. Find the average purchase price for each financial instrument
SELECT InstrumentID, AVG(PurchasePrice) AS AveragePurchasePrice
FROM USER_INVESTMENT
GROUP BY InstrumentID;

-- 5. Find the total quantity of each financial instrument bought by users
SELECT InstrumentID, SUM(Quantity) AS TotalQuantity
FROM USER_INVESTMENT
GROUP BY InstrumentID;

-- 6. Find the user who bought the highest quantity of a particular financial instrument (e.g., InstrumentID = 1)
SELECT UserID, SUM(Quantity) AS TotalQuantity
FROM USER_INVESTMENT
WHERE InstrumentID = 1
GROUP BY UserID
ORDER BY TotalQuantity DESC
LIMIT 1;

-- 7. Find the financial instrument that has the highest trading volume on a particular date (e.g., '2023-11-01')
SELECT InstrumentID, Volume
FROM MARKET_DATA
WHERE Date = '2023-11-01'
ORDER BY Volume DESC
LIMIT 1;

-- 8. Find the total number of reports generated by each user
SELECT UserID, COUNT(*) AS TotalReports
FROM REPORT
GROUP BY UserID;

-- 9. Find the user who has generated the most reports
SELECT UserID, COUNT(*) AS TotalReports
FROM REPORT
GROUP BY UserID
ORDER BY TotalReports DESC
LIMIT 1;

-- 10. Find the financial instrument with the highest price fluctuation on a particular date (e.g., '2023-11-01')
SELECT InstrumentID, (High - Low) AS PriceFluctuation
FROM MARKET_DATA
WHERE Date = '2023-11-01'
ORDER BY PriceFluctuation DESC
LIMIT 1;